### ISSUE TITLE
settings are not saved

### ISSUE THREAD

**Issue by xleb-normal** [Nukebob3/TetrisMC#1]
When I change any setting and go back, all mod settings are reset

**Comment by Nukebob3** [comment]
I think that's been fixed, try the latest version

**Comment by xleb-normal** [comment]
> I think that's been fixed, try the latest version

this is not fixed in the latest version (1.0.5)

https://github.com/user-attachments/assets/5d0890dd-7d80-4973-b53b-74dc56c8fe9b

**Comment by xleb-normal** [comment]
@Nukebob3

**Comment by Nukebob3** [comment]
oki I'll work on fixing it

**Comment by Nukebob3** [comment]
@Xleby4ek could you please provide the logs from when you try to update the settings

**Comment by Nukebob3** [comment]
no i've found the issue i believe, @Xleby4ek can you please join my discord to test this version before I release it. Just so that I know it works for you too

**Comment by xleb-normal** [comment]
> no i've found the issue i believe, @Xleby4ek can you please join my discord to test this version before I release it. Just so that I know it works for you too

I'm on the server, my Discord nickname is Xleb_Normal
