### ISSUE TITLE
Tetris textures mode

### ISSUE THREAD

**Issue by maplesyrup-17** [Nukebob3/TetrisMC#2]
Pls, could you add a mode where the textures are like in normal Tetris instead of Minecraft textures?

**Comment by Nukebob3** [comment]
That's a great idea. I'll work on it

**Comment by Nukebob3** [comment]
Should the coloured blocks be always a minecraft block texture still? Just same block

**Comment by maplesyrup-17** [comment]
It could be like all blocks with the same shape have the same texture, so there's not so much differents textures on screen

**Comment by Nukebob3** [comment]
Oki, I'll work on it later

**Comment by Nukebob3** [comment]
![Screenshot_20241023_080603_Google~2](https://github.com/user-attachments/assets/97cb7902-b018-4bed-adc7-2d3d9811c5de)
What if I use the minecraft mineral blocks like diamond, amethyst, gold, redstone, lapis, emerald, copper

**Comment by maplesyrup-17** [comment]
That would be a great idea!

**Comment by Nukebob3** [comment]
newest version check it out. I'd appreciate your feedback!
[https://modrinth.com/mod/tetrismc/version/VeAZcy6a](url)

**Comment by maplesyrup-17** [comment]
It works really well, thanks!!
