### ISSUE TITLE
Crash in 1.21.2

### ISSUE THREAD

**Issue by MiSosumi** [Nukebob3/TetrisMC#3]
There seems to be a confict with my [other mods](https://imgur.com/a/iOKpVru) in 1.21.2

**Comment by Nukebob3** [comment]
Can I please see the logs when you client crashes

**Comment by MiSosumi** [comment]
Here you go:- https://paste.ee/p/sU0WI

**Comment by Nukebob3** [comment]
yeah not compatible with 1.21.2
